-- Wood Heaven Farms Database Setup

-- 1. Site Settings
CREATE TABLE site_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hero_title TEXT NOT NULL,
    hero_subtitle TEXT NOT NULL,
    hero_bg_url TEXT NOT NULL,
    whatsapp_number TEXT NOT NULL,
    whatsapp_prefill TEXT NOT NULL,
    teaser_bg_url TEXT NOT NULL DEFAULT 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&q=80&w=2000',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert initial mock data
INSERT INTO site_settings (id, hero_title, hero_subtitle, hero_bg_url, whatsapp_number, whatsapp_prefill, teaser_bg_url)
VALUES (1, 'wood heaven Farms', 'Private Luxury farmhouse stay and event estate', 'https://images.unsplash.com/photo-1536431311719-398b6704d40f?auto=format&fit=crop&q=80&w=2000', '918852021119', 'Hi Wood Heaven Farms, I want to enquire about a booking.', 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?auto=format&fit=crop&q=80&w=2000')
ON CONFLICT (id) DO NOTHING;

-- 2. Location Settings
CREATE TABLE location_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    short_area TEXT NOT NULL,
    address TEXT NOT NULL,
    airport_time TEXT NOT NULL,
    railway_time TEXT NOT NULL,
    city_time TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

INSERT INTO location_settings (id, short_area, address, airport_time, railway_time, city_time)
VALUES (1, 'Sikar Road, Jaipur', 'Wood Heaven Farms, 621, 622, Green Triveni, Opposite Ashiana Greens, Sikar Road, Jaipur, Rajasthan 302013', '45m', '30m', '15m')
ON CONFLICT (id) DO NOTHING;

-- 3. Gallery Media
CREATE TABLE gallery_media (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    url TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('image', 'video')),
    category TEXT NOT NULL,
    label TEXT NOT NULL,
    thumbnail TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Experiences
CREATE TABLE experiences (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Testimonials
CREATE TABLE testimonials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Enquiries
CREATE TABLE enquiries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT NOT NULL,
    message TEXT,
    page_source TEXT DEFAULT 'website',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Home Highlights
CREATE TABLE home_highlights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    label TEXT NOT NULL,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE location_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE home_highlights ENABLE ROW LEVEL SECURITY;

-- Policies for Public Read Access
CREATE POLICY "Public Read Access" ON site_settings FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON location_settings FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON gallery_media FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON experiences FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON testimonials FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON home_highlights FOR SELECT USING (true);

-- Policy for Public Insert (Enquiries)
CREATE POLICY "Public Insert Access" ON enquiries FOR INSERT WITH CHECK (true);

-- Policies for Admin Access (Requires Authentication)
-- (Assuming an admin role or just authenticated users for now)
CREATE POLICY "Admin All Access" ON site_settings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Access" ON location_settings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Access" ON gallery_media FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Access" ON experiences FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Access" ON testimonials FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Access" ON enquiries FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin All Access" ON home_highlights FOR ALL USING (auth.role() = 'authenticated');
